/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include <thirft-gen/test_constants.h>

namespace rock {

const testConstants g_test_constants;

testConstants::testConstants() {
}

} // namespace

